export const SEND_MESSAGE = 'SEND_MESSAGE';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const TRANFER_CALL_DATA = 'TRANFER_CALL_DATA';
export const MAKE_CALL_REQUEST = 'MAKE_CALL_REQUEST';
export const JOIN_CALL_REQUEST = 'JOIN_CALL_REQUEST';
export const END_CALL_REQUEST  = 'END_CALL_REQUEST';